services:
  - type: web
    name: mb2csv-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /docs      # FastAPI swagger를 헬스체크로 사용
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
